title: "[Project Name]"
labels: ["Add new library"]
body:
  - type: markdown
    attributes:
      value: |
        Please complete this form!
  - type: input
    id: has-id
    attributes:
      label: Repo-URL
      description: Repository URL
    validations:
      required: true
  - type: textarea
    id: highlights
    attributes:
      label: Description of your project
      description: "Write a short description of your project!"
      render: bash
    validations:
      required: true
  - type: textarea
    id: highlights
    attributes:
      label: Highlights of your project
      description: "What usefull features your project has?"
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Markdown header
        And some more markdown
  - type: dropdown
    id: pip
    attributes:
      label: Is the project uploaded to pip?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: docs
      options:
        - label: The repository has proper documentation
          required: true
  - type: markdown
    attributes:
      value: |
        ### Thank you!
        _This form will be checked soon..._
